_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 24
                - 55
            "4": 3.9.6
            "5": 0.19.4
            "8":
                - 1
                - 5
            "12": 0.19.4
            "13": darwin-x86_64
        viz:
            confusion_matrix:
                historyFieldSettings:
                    key: confusion_matrix
                    x-axis: _step
                id: wandb/confusion_matrix/v1
